#!/bin/bash
#SBATCH -p long
#SBATCH --time=2-00:00:00
#SBATCH --error=error.txt

module load anaconda/3

conda activate presto-v3

python -m scripts.copy_tifs --src_folder "tifs0" --dest_folder "tifs_all_bands"
python -m scripts.copy_tifs --src_folder "tifs1000" --dest_folder "tifs_all_bands"
python -m scripts.copy_tifs --src_folder "tifs2000" --dest_folder "tifs_all_bands"
python -m scripts.copy_tifs --src_folder "tifs3000" --dest_folder "tifs_all_bands"
python -m scripts.copy_tifs --src_folder "tifs4000" --dest_folder "tifs_all_bands"
python -m scripts.copy_tifs --src_folder "tifs5000" --dest_folder "tifs_all_bands"
python -m scripts.copy_tifs --src_folder "tifs6000" --dest_folder "tifs_all_bands"
python -m scripts.copy_tifs --src_folder "tifs7000" --dest_folder "tifs_all_bands"
python -m scripts.copy_tifs --src_folder "tifs8000" --dest_folder "tifs_all_bands"
python -m scripts.copy_tifs --src_folder "tifs9000" --dest_folder "tifs_all_bands"
python -m scripts.copy_tifs --src_folder "tifs10000" --dest_folder "tifs_all_bands"
python -m scripts.copy_tifs --src_folder "tifs11000" --dest_folder "tifs_all_bands"
python -m scripts.copy_tifs --src_folder "tifs12000" --dest_folder "tifs_all_bands"
python -m scripts.copy_tifs --src_folder "tifs13000" --dest_folder "tifs_all_bands"
python -m scripts.copy_tifs --src_folder "tifs14000" --dest_folder "tifs_all_bands"
python -m scripts.copy_tifs --src_folder "tifs15000" --dest_folder "tifs_all_bands"
python -m scripts.copy_tifs --src_folder "tifs16000" --dest_folder "tifs_all_bands"
python -m scripts.copy_tifs --src_folder "tifs17000" --dest_folder "tifs_all_bands"
python -m scripts.copy_tifs --src_folder "tifs18000" --dest_folder "tifs_all_bands"
python -m scripts.copy_tifs --src_folder "tifs19000" --dest_folder "tifs_all_bands"
python -m scripts.copy_tifs --src_folder "tifs20000" --dest_folder "tifs_all_bands"
python -m scripts.copy_tifs --src_folder "tifs21000" --dest_folder "tifs_all_bands"
python -m scripts.copy_tifs --src_folder "tifs22000" --dest_folder "tifs_all_bands"
python -m scripts.copy_tifs --src_folder "tifs23000" --dest_folder "tifs_all_bands"
python -m scripts.copy_tifs --src_folder "tifs24000" --dest_folder "tifs_all_bands"
python -m scripts.copy_tifs --src_folder "tifs25000" --dest_folder "tifs_all_bands"
python -m scripts.copy_tifs --src_folder "tifs26000" --dest_folder "tifs_all_bands"
python -m scripts.copy_tifs --src_folder "tifs27000" --dest_folder "tifs_all_bands"
python -m scripts.copy_tifs --src_folder "tifs28000" --dest_folder "tifs_all_bands"
python -m scripts.copy_tifs --src_folder "tifs29000" --dest_folder "tifs_all_bands"
python -m scripts.copy_tifs --src_folder "tifs30000" --dest_folder "tifs_all_bands"
python -m scripts.copy_tifs --src_folder "tifs31000" --dest_folder "tifs_all_bands"
python -m scripts.copy_tifs --src_folder "tifs32000" --dest_folder "tifs_all_bands"
python -m scripts.copy_tifs --src_folder "tifs33000" --dest_folder "tifs_all_bands"
python -m scripts.copy_tifs --src_folder "tifs34000" --dest_folder "tifs_all_bands"
python -m scripts.copy_tifs --src_folder "tifs35000" --dest_folder "tifs_all_bands"
python -m scripts.copy_tifs --src_folder "tifs36000" --dest_folder "tifs_all_bands"
python -m scripts.copy_tifs --src_folder "tifs37000" --dest_folder "tifs_all_bands"
python -m scripts.copy_tifs --src_folder "tifs38000" --dest_folder "tifs_all_bands"
python -m scripts.copy_tifs --src_folder "tifs39000" --dest_folder "tifs_all_bands"
python -m scripts.copy_tifs --src_folder "tifs40000" --dest_folder "tifs_all_bands"
python -m scripts.copy_tifs --src_folder "tifs41000" --dest_folder "tifs_all_bands"
python -m scripts.copy_tifs --src_folder "tifs42000" --dest_folder "tifs_all_bands"
python -m scripts.copy_tifs --src_folder "tifs43000" --dest_folder "tifs_all_bands"
python -m scripts.copy_tifs --src_folder "tifs44000" --dest_folder "tifs_all_bands"
python -m scripts.copy_tifs --src_folder "tifs45000" --dest_folder "tifs_all_bands"
python -m scripts.copy_tifs --src_folder "tifs46000" --dest_folder "tifs_all_bands"
python -m scripts.copy_tifs --src_folder "tifs47000" --dest_folder "tifs_all_bands"
python -m scripts.copy_tifs --src_folder "tifs48000" --dest_folder "tifs_all_bands"
python -m scripts.copy_tifs --src_folder "tifs49000" --dest_folder "tifs_all_bands"
python -m scripts.copy_tifs --src_folder "tifs50000" --dest_folder "tifs_all_bands"
python -m scripts.copy_tifs --src_folder "tifs51000" --dest_folder "tifs_all_bands"