VIT_PATCH_SIZE = 16
PRESTO_INPUT_SIZE = 32
CROMA_INPUT_SIZE = 128
NUM_VIT_PATCHES_PER_CROMA_DIM = int(CROMA_INPUT_SIZE / VIT_PATCH_SIZE)
NUM_TIMESTEPS = 12
BASE_GSD = 10

assert CROMA_INPUT_SIZE % VIT_PATCH_SIZE == 0
assert PRESTO_INPUT_SIZE % VIT_PATCH_SIZE == 0

DEFAULT_SEED = 42
