name: Mypy

on:
  pull_request:
    branches: [main]

jobs:
  Mypy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: make install-all

      - name: Mypy
        run: make mypy

